using System.ComponentModel.DataAnnotations;

namespace backend.Models;

public class Recording
{
    [Key] // Primary key and auto-generated by the database
    public long Id { get; set; }

    [Required]
    public string Path { get; set; }

    [Required]
    public string Name { get; set; }

    [MaxLength(500)]
    public string? Description { get; set; }

    [Required]
    public DateTime StartDateTime { get; set; }

    [Required]
    public DateTime EndDateTime { get; set; }

    [Required]
    public TimeSpan Duration { get; set; }

    [Required]
    public long Size { get; set; }

    public Recording()
    {
    }





}
